import type { Metadata } from "next";
import { ThemeProvider } from "@/components/theme-provider";
import { Inter as FontSans } from "next/font/google";
import { cn } from "../lib/utils";
import "./globals.css";
import NavBar from "@/components/nav-bar";
import SessionProvider from "@/components/sessionProvider";
import { getServerSession } from "next-auth";
const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(); 

  return (
    <html suppressHydrationWarning lang="en" className="h-full">
      <body
        className={cn(
          " bg-background font-sans antialiased h-full relative ",
          fontSans.variable
        )}
      >
        <SessionProvider session={session}>
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            // disableTransitionOnChange
            >
            <NavBar/>
            {children}
          </ThemeProvider>
            </SessionProvider>
      </body>
    </html>
  );
}
